# fly.toml app configuration file generated for synthlang-proxy
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'synthlang-proxy'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  HOST = "0.0.0.0"
  DEBUG = "false"
  USE_SQLITE = "1"
  SQLITE_PATH = "sqlite+aiosqlite:///./data/synthlang_proxy.db"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = "synthlang_data"
  destination = "/app/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1